/*
 * generated by Xtext 2.35.0
 */
package org.pnpl.model.variability.editor.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class PNPL_variabilityProposalProvider extends AbstractPNPL_variabilityProposalProvider {
}
