/*
 * generated by Xtext 2.35.0
 */
package org.pnpl.model.variability.editor.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class PNPL_variabilityUiModule extends AbstractPNPL_variabilityUiModule {
}
