/*
 * generated by Xtext 2.36.0
 */
package org.pnpl.model.variability.editor.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPNPL_variabilityScopeProvider extends DelegatingScopeProvider {
}
