/*
 * generated by Xtext 2.36.0
 */
package org.pnpl.model.variability.editor.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PNPL_variabilityAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/pnpl/model/variability/editor/parser/antlr/internal/InternalPNPL_variability.tokens");
	}
}
