/*
 * generated by Xtext 2.36.0
 */
package org.pnpl.model.variability.editor.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.pnpl.model.variability.editor.parser.antlr.internal.InternalPNPL_variabilityParser;
import org.pnpl.model.variability.editor.services.PNPL_variabilityGrammarAccess;

public class PNPL_variabilityParser extends AbstractAntlrParser {

	@Inject
	private PNPL_variabilityGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPNPL_variabilityParser createParser(XtextTokenStream stream) {
		return new InternalPNPL_variabilityParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Variability";
	}

	public PNPL_variabilityGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PNPL_variabilityGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
