/*
 * generated by Xtext 2.35.0
 */
package org.pnpl.model.variability.editor.ide


/**
 * Use this class to register ide components.
 */
class PNPL_variabilityIdeModule extends AbstractPNPL_variabilityIdeModule {
}
